#!/bin/bash

echo "=== Build Script Debug ==="
echo "Available environment variables:"
printenv | grep REACT_APP || echo "No REACT_APP variables found"
echo "=========================="

# Export all REACT_APP variables explicitly
export REACT_APP_GRADE_SECTION_PASSCODE="$REACT_APP_GRADE_SECTION_PASSCODE"
export REACT_APP_STUDENTS_PASSCODE="$REACT_APP_STUDENTS_PASSCODE"
export REACT_APP_STAFF_PASSCODE="$REACT_APP_STAFF_PASSCODE"
export REACT_APP_TRANSCRIPT_PASSCODE="$REACT_APP_TRANSCRIPT_PASSCODE"
export REACT_APP_GRADE_SHEET_PASSCODE="$REACT_APP_GRADE_SHEET_PASSCODE"
export REACT_APP_ROSTER_SUMMARY_PASSCODE="$REACT_APP_ROSTER_SUMMARY_PASSCODE"
export REACT_APP_PAYMENTS_PASSCODE="$REACT_APP_PAYMENTS_PASSCODE"
export REACT_APP_PROMOTION_PASSCODE="$REACT_APP_PROMOTION_PASSCODE"
export REACT_APP_OTHER_PAYMENTS_PASSCODE="$REACT_APP_OTHER_PAYMENTS_PASSCODE"
export REACT_APP_TVET_PAYMENTS_PASSCODE="$REACT_APP_TVET_PAYMENTS_PASSCODE"
export REACT_APP_FINANCIAL_REPORT_PASSCODE="$REACT_APP_FINANCIAL_REPORT_PASSCODE"

echo "After export:"
printenv | grep REACT_APP || echo "No REACT_APP variables found after export"

cd client
npm install
npm run build