#!/bin/bash

echo "=== Build Script Started ==="
echo "Available REACT_APP variables:"
env | grep REACT_APP || echo "No REACT_APP variables found"

# Install root dependencies
npm install

# Change to client directory and build with environment
cd client

echo "=== In client directory ==="
echo "Environment check:"
env | grep REACT_APP || echo "No REACT_APP variables in client context"

# Install client dependencies
npm install

# Build with explicit environment variables
REACT_APP_GRADE_SECTION_PASSCODE="$REACT_APP_GRADE_SECTION_PASSCODE" \
REACT_APP_STUDENTS_PASSCODE="$REACT_APP_STUDENTS_PASSCODE" \
REACT_APP_STAFF_PASSCODE="$REACT_APP_STAFF_PASSCODE" \
REACT_APP_TRANSCRIPT_PASSCODE="$REACT_APP_TRANSCRIPT_PASSCODE" \
REACT_APP_GRADE_SHEET_PASSCODE="$REACT_APP_GRADE_SHEET_PASSCODE" \
REACT_APP_ROSTER_SUMMARY_PASSCODE="$REACT_APP_ROSTER_SUMMARY_PASSCODE" \
REACT_APP_PAYMENTS_PASSCODE="$REACT_APP_PAYMENTS_PASSCODE" \
REACT_APP_PROMOTION_PASSCODE="$REACT_APP_PROMOTION_PASSCODE" \
REACT_APP_OTHER_PAYMENTS_PASSCODE="$REACT_APP_OTHER_PAYMENTS_PASSCODE" \
REACT_APP_TVET_PAYMENTS_PASSCODE="$REACT_APP_TVET_PAYMENTS_PASSCODE" \
REACT_APP_FINANCIAL_REPORT_PASSCODE="$REACT_APP_FINANCIAL_REPORT_PASSCODE" \
npm run build

echo "=== Build completed ==="