//Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

//email Verification
export const EMAIL_VERIFICATION_REQUEST_SENT = 'EMAIL_VERIFICATION_REQUEST_SENT';
export const EMAIL_VERIFICATION_REQUEST_FAILED = 'EMAIL_VERIFICATION_REQUEST_FAILED';
export const EMAIL_VERIFICATION_CONFIRMED = 'EMAIL_VERIFICATION_CONFIRMED';
export const EMAIL_VERIFICATION_CONFIRM_FAILED = 'EMAIL_VERIFICATION_CONFIRM_FAILED';

//Password Reset
export const  FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const  RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';


//General
export const AUTH_SET_LOADING = 'AUTH_SET_LOADING'; // For auth specific loading
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE';
export const ADMIN_SET_LOADING = 'ADMIN_SET_LOADING';

// admin profile
export const GET_ADMIN_PROFILE = 'GET_ADMIN_PROFILE';
export const GET_ADMIN_PROFILE_SUCCESS = 'GET_ADMIN_PROFILE_SUCCESS';
export const GET_ADMIN_PROFILE_FAIL = 'GET_ADMIN_PROFILE_FAIL';
export const UPDATE_ADMIN_PROFILE = 'UPDATE_ADMIN_PROFILE';
export const UPDATE_ADMIN_PROFILE_SUCCESS = 'UPDATE_ADMIN_PROFILE_SUCCESS';
export const UPDATE_ADMIN_PROFILE_FAIL = 'UPDATE_ADMIN_PROFILE_FAIL';
export const UPLOAD_ADMIN_PHOTO = 'UPLOAD_ADMIN_PHOTO';
export const UPLOAD_ADMIN_PHOTO_SUCCESS = 'UPLOAD_ADMIN_PHOTO_SUCCESS';
export const UPLOAD_ADMIN_PHOTO_FAIL = 'UPLOAD_ADMIN_PHOTO_FAIL';
export const CLEAR_ADMIN_PROFILE = 'CLEAR_ADMIN_PROFILE';
export const ADMIN_PROFILE_ERROR = 'ADMIN_PROFILE_ERROR';
export const CLEAR_ADMINS = 'CLEAR_ADMINS';

// Admin listings
export const GET_ADMINS = 'GET_ADMINS';
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS';
export const GET_ADMINS_FAIL = 'GET_ADMINS_FAIL';
export const SEARCH_ADMINS = 'SEARCH_ADMINS';
export const SEARCH_ADMINS_SUCCESS = 'SEARCH_ADMINS_SUCCESS';
export const SEARCH_ADMINS_FAIL = 'SEARCH_ADMINS_FAIL';
export const GET_ADMIN = 'GET_ADMIN';
export const GET_ADMIN_FAIL = 'GET_ADMIN_FAIL';
