//Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

//email Verification
export const EMAIL_VERIFICATION_REQUEST_SENT = 'EMAIL_VERIFICATION_REQUEST_SENT';
export const EMAIL_VERIFICATION_REQUEST_FAILED = 'EMAIL_VERIFICATION_REQUEST_FAILED';
export const EMAIL_VERIFICATION_CONFIRMED = 'EMAIL_VERIFICATION_CONFIRMED';
export const EMAIL_VERIFICATION_CONFIRM_FAILED = 'EMAIL_VERIFICATION_CONFIRM_FAILED';

//Password Reset
export const  FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const  RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';


//General
export const AUTH_SET_LOADING = 'AUTH_SET_LOADING'; // For auth specific loading
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE';
export const ADMIN_SET_LOADING = 'ADMIN_SET_LOADING';

// admin profile
export const GET_ADMIN_PROFILE = 'GET_ADMIN_PROFILE';
export const GET_ADMIN_PROFILE_SUCCESS = 'GET_ADMIN_PROFILE_SUCCESS';
export const GET_ADMIN_PROFILE_FAIL = 'GET_ADMIN_PROFILE_FAIL';
export const UPDATE_ADMIN_PROFILE = 'UPDATE_ADMIN_PROFILE';
export const UPDATE_ADMIN_PROFILE_SUCCESS = 'UPDATE_ADMIN_PROFILE_SUCCESS';
export const UPDATE_ADMIN_PROFILE_FAIL = 'UPDATE_ADMIN_PROFILE_FAIL';
export const UPLOAD_ADMIN_PHOTO = 'UPLOAD_ADMIN_PHOTO';
export const UPLOAD_ADMIN_PHOTO_SUCCESS = 'UPLOAD_ADMIN_PHOTO_SUCCESS';
export const UPLOAD_ADMIN_PHOTO_FAIL = 'UPLOAD_ADMIN_PHOTO_FAIL';
export const CLEAR_ADMIN_PROFILE = 'CLEAR_ADMIN_PROFILE';
export const ADMIN_PROFILE_ERROR = 'ADMIN_PROFILE_ERROR';
export const CLEAR_ADMINS = 'CLEAR_ADMINS';

// Admin listings
export const GET_ADMINS = 'GET_ADMINS';
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS';
export const GET_ADMINS_FAIL = 'GET_ADMINS_FAIL';
export const SEARCH_ADMINS = 'SEARCH_ADMINS';
export const SEARCH_ADMINS_SUCCESS = 'SEARCH_ADMINS_SUCCESS';
export const SEARCH_ADMINS_FAIL = 'SEARCH_ADMINS_FAIL';
export const GET_ADMIN = 'GET_ADMIN';
export const GET_ADMIN_FAIL = 'GET_ADMIN_FAIL';

// Student Loading
export const STUDENT_SET_LOADING = 'STUDENT_SET_LOADING';

// Create Student
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAIL = 'CREATE_STUDENT_FAIL';

// Get Students
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL';

// Get Single Student
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_FAIL = 'GET_STUDENT_FAIL';

// Update Student
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL';

// Delete Student
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL';

// Search Students
export const SEARCH_STUDENTS_SUCCESS = 'SEARCH_STUDENTS_SUCCESS';
export const SEARCH_STUDENTS_FAIL = 'SEARCH_STUDENTS_FAIL';

// Clear and Error Handling
export const CLEAR_STUDENTS = 'CLEAR_STUDENTS';
export const STUDENT_ERROR = 'STUDENT_ERROR';
export const CLEAR_STUDENT_ERRORS = 'CLEAR_STUDENT_ERRORS';
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS';
export const GET_STATS_FAIL = 'GET_STATS_FAIL'
export const STATS_LOADING = 'STATS_LOADING';

// Staff Loading
export const STAFF_SET_LOADING = 'STAFF_SET_LOADING';

// Create Staff
export const CREATE_STAFF_SUCCESS = 'CREATE_STAFF_SUCCESS';
export const CREATE_STAFF_FAIL = 'CREATE_STAFF_FAIL';

// Get Staff
export const GET_STAFF_SUCCESS = 'GET_STAFF_SUCCESS';
export const GET_STAFF_FAIL = 'GET_STAFF_FAIL';

// Get Single Staff
export const GET_SINGLE_STAFF_SUCCESS = 'GET_SINGLE_STAFF_SUCCESS';
export const GET_SINGLE_STAFF_FAIL = 'GET_SINGLE_STAFF_FAIL';

// Update Staff
export const UPDATE_STAFF_SUCCESS = 'UPDATE_STAFF_SUCCESS';
export const UPDATE_STAFF_FAIL = 'UPDATE_STAFF_FAIL';

// Delete Staff
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';
export const DELETE_STAFF_FAIL = 'DELETE_STAFF_FAIL';

// Search Staff
export const SEARCH_STAFF_SUCCESS = 'SEARCH_STAFF_SUCCESS';
export const SEARCH_STAFF_FAIL = 'SEARCH_STAFF_FAIL';

// Staff Audit Trail
export const GET_STAFF_AUDIT_SUCCESS = 'GET_STAFF_AUDIT_SUCCESS';
export const GET_STAFF_AUDIT_FAIL = 'GET_STAFF_AUDIT_FAIL';

// Clear and Error Handling
export const CLEAR_STAFF = 'CLEAR_STAFF';
export const STAFF_ERROR = 'STAFF_ERROR';
export const CLEAR_STAFF_ERRORS = 'CLEAR_STAFF_ERRORS';



// Grade Loading
export const GRADE_SET_LOADING = 'GRADE_SET_LOADING';
export const GRADE_SET_ERROR = 'GRADE_SET_ERROR';
export const GRADE_CLEAR_ERROR = 'GRADE_CLEAR_ERROR';

// Create Grade
export const CREATE_GRADE_SUCCESS = 'CREATE_GRADE_SUCCESS';
export const CREATE_GRADE_FAIL = 'CREATE_GRADE_FAIL';

// Get All Grades
export const GET_ALL_GRADES_SUCCESS = 'GET_ALL_GRADES_SUCCESS';
export const GET_ALL_GRADES_FAIL = 'GET_ALL_GRADES_FAIL';

// Get Single Grade
export const GET_GRADE_BY_ID_SUCCESS = 'GET_GRADE_BY_ID_SUCCESS';
export const GET_GRADE_BY_ID_FAIL = 'GET_GRADE_BY_ID_FAIL';

// Update Grade
export const UPDATE_GRADE_SUCCESS = 'UPDATE_GRADE_SUCCESS';
export const UPDATE_GRADE_FAIL = 'UPDATE_GRADE_FAIL';

// Delete Grade
export const DELETE_GRADE_SUCCESS = 'DELETE_GRADE_SUCCESS';
export const DELETE_GRADE_FAIL = 'DELETE_GRADE_FAIL';

// Student Grades
export const GET_STUDENT_GRADES_SUCCESS = 'GET_STUDENT_GRADES_SUCCESS';
export const GET_STUDENT_GRADES_FAIL = 'GET_STUDENT_GRADES_FAIL';

// Student Performance
export const GET_STUDENT_PERFORMANCE_SUCCESS = 'GET_STUDENT_PERFORMANCE_SUCCESS';
export const GET_STUDENT_PERFORMANCE_FAIL = 'GET_STUDENT_PERFORMANCE_FAIL';

// Class Performance Analytics
export const GET_CLASS_PERFORMANCE_SUCCESS = 'GET_CLASS_PERFORMANCE_SUCCESS';
export const GET_CLASS_PERFORMANCE_FAIL = 'GET_CLASS_PERFORMANCE_FAIL';

// Grade Pagination
export const GRADE_SET_PAGINATION = 'GRADE_SET_PAGINATION';

// Grade Filters
export const GRADE_SET_FILTERS = 'GRADE_SET_FILTERS';
export const GRADE_CLEAR_FILTERS = 'GRADE_CLEAR_FILTERS';

// Clear and Error Handling
export const CLEAR_GRADES = 'CLEAR_GRADES';
export const GRADE_ERROR = 'GRADE_ERROR';
export const CLEAR_GRADE_ERRORS = 'CLEAR_GRADE_ERRORS';
export const GRADE_SEARCH_STUDENTS_SUCCESS = 'GRADE_SEARCH_STUDENTS_SUCCESS';
export const GRADE_SEARCH_STUDENTS_FAIL = 'GRADE_SEARCH_STUDENTS_FAIL';

// Report Card
export const GET_REPORT_CARD_DATA_REQUEST = 'GET_REPORT_CARD_DATA_REQUEST';
export const GET_REPORT_CARD_DATA_SUCCESS = 'GET_REPORT_CARD_DATA_SUCCESS';
export const GET_REPORT_CARD_DATA_FAIL = 'GET_REPORT_CARD_DATA_FAIL';
export const CLEAR_REPORT_CARD_ERRORS = 'CLEAR_REPORT_CARD_ERRORS';


// Announcements
export const ANNOUNCEMENT_SET_LOADING = 'ANNOUNCEMENT_SET_LOADING';
export const GET_ANNOUNCEMENTS_SUCCESS = 'GET_ANNOUNCEMENTS_SUCCESS';
export const GET_ANNOUNCEMENTS_FAIL = 'GET_ANNOUNCEMENTS_FAIL';
export const CREATE_ANNOUNCEMENT_SUCCESS = 'CREATE_ANNOUNCEMENT_SUCCESS';
export const CREATE_ANNOUNCEMENT_FAIL = 'CREATE_ANNOUNCEMENT_FAIL';
export const DELETE_ANNOUNCEMENT_SUCCESS = 'DELETE_ANNOUNCEMENT_SUCCESS';
export const DELETE_ANNOUNCEMENT_FAIL = 'DELETE_ANNOUNCEMENT_FAIL';
export const CLEAR_ANNOUNCEMENT_ERRORS = 'CLEAR_ANNOUNCEMENT_ERRORS'


// Action Types 
export const GET_PROMOTION_PREVIEW_REQUEST = 'GET_PROMOTION_PREVIEW_REQUEST';
export const GET_PROMOTION_PREVIEW_SUCCESS = 'GET_PROMOTION_PREVIEW_SUCCESS';
export const GET_PROMOTION_PREVIEW_FAIL = 'GET_PROMOTION_PREVIEW_FAIL';

export const PROCESS_STUDENT_PROMOTION_REQUEST = 'PROCESS_STUDENT_PROMOTION_REQUEST';
export const PROCESS_STUDENT_PROMOTION_SUCCESS = 'PROCESS_STUDENT_PROMOTION_SUCCESS';
export const PROCESS_STUDENT_PROMOTION_FAIL = 'PROCESS_STUDENT_PROMOTION_FAIL';

export const GET_YEARLY_AVERAGES_REQUEST = 'GET_YEARLY_AVERAGES_REQUEST';
export const GET_YEARLY_AVERAGES_SUCCESS = 'GET_YEARLY_AVERAGES_SUCCESS';
export const GET_YEARLY_AVERAGES_FAIL = 'GET_YEARLY_AVERAGES_FAIL';

export const PROCESS_BATCH_PROMOTIONS_REQUEST = 'PROCESS_BATCH_PROMOTIONS_REQUEST';
export const PROCESS_BATCH_PROMOTIONS_SUCCESS = 'PROCESS_BATCH_PROMOTIONS_SUCCESS';
export const PROCESS_BATCH_PROMOTIONS_FAIL = 'PROCESS_BATCH_PROMOTIONS_FAIL';

export const GET_ELIGIBLE_STUDENTS_REQUEST = 'GET_ELIGIBLE_STUDENTS_REQUEST';
export const GET_ELIGIBLE_STUDENTS_SUCCESS = 'GET_ELIGIBLE_STUDENTS_SUCCESS';
export const GET_ELIGIBLE_STUDENTS_FAIL = 'GET_ELIGIBLE_STUDENTS_FAIL';

export const CLEAR_PROMOTION_DATA = 'CLEAR_PROMOTION_DATA';